export const MEXICAN_STATES_AND_CITIES: Record<string, string[]> = {
  "Aguascalientes": ["Aguascalientes", "Jesús María", "Calvillo", "Pabellón de Arteaga"],
  "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Tecate", "Playas de Rosarito"],
  "Baja California Sur": ["La Paz", "Los Cabos", "Ciudad Constitución", "Loreto", "Santa Rosalía"],
  "Campeche": ["Campeche", "Ciudad del Carmen", "Champotón", "Escárcega"],
  "Chiapas": ["Tuxtla Gutiérrez", "Tapachula", "San Cristóbal de las Casas", "Comitán", "Palenque"],
  "Chihuahua": ["Chihuahua", "Ciudad Juárez", "Delicias", "Cuauhtémoc", "Parral"],
  "Ciudad de México": ["Álvaro Obregón", "Azcapotzalco", "Benito Juárez", "Coyoacán", "Cuauhtémoc", "Gustavo A. Madero", "Miguel Hidalgo", "Tlalpan", "Venustiano Carranza", "Xochimilco"],
  "Coahuila": ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Ciudad Acuña"],
  "Colima": ["Colima", "Manzanillo", "Villa de Álvarez", "Tecomán"],
  "Durango": ["Durango", "Gómez Palacio", "Lerdo"],
  "Estado de México": ["Toluca", "Ecatepec", "Naucalpan", "Tlalnepantla", "Nezahualcóyotl", "Metepec", "Huixquilucan", "Cuautitlán Izcalli"],
  "Guanajuato": ["León", "Irapuato", "Celaya", "Guanajuato", "San Miguel de Allende", "Salamanca"],
  "Guerrero": ["Acapulco", "Chilpancingo", "Iguala", "Zihuatanejo", "Taxco"],
  "Hidalgo": ["Pachuca", "Tulancingo", "Tula de Allende", "Ciudad Sahagún"],
  "Jalisco": ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta", "Tlajomulco de Zúñiga", "Lagos de Moreno", "Tepatitlán"],
  "Michoacán": ["Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas", "Pátzcuaro"],
  "Morelos": ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Tepoztlán"],
  "Nayarit": ["Tepic", "Bahía de Banderas", "Compostela", "Ixtlán del Río"],
  "Nuevo León": ["Monterrey", "San Pedro Garza García", "San Nicolás de los Garza", "Guadalupe", "Apodaca", "Santa Catarina"],
  "Oaxaca": ["Oaxaca de Juárez", "Salina Cruz", "Juchitán", "Tuxtepec", "Huatulco", "Puerto Escondido"],
  "Puebla": ["Puebla", "Cholula", "Tehuacán", "Atlixco", "San Martín Texmelucan"],
  "Querétaro": ["Santiago de Querétaro", "San Juan del Río", "Corregidora", "El Marqués", "Tequisquiapan"],
  "Quintana Roo": ["Cancún", "Playa del Carmen", "Chetumal", "Cozumel", "Tulum"],
  "San Luis Potosí": ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles", "Matehuala"],
  "Sinaloa": ["Culiacán", "Mazatlán", "Los Mochis", "Guasave"],
  "Sonora": ["Hermosillo", "Ciudad Obregón", "Nogales", "San Luis Río Colorado", "Guaymas", "Navojoa"],
  "Tabasco": ["Villahermosa", "Cárdenas", "Comalcalco", "Macuspana"],
  "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico", "Ciudad Victoria", "Ciudad Madero"],
  "Tlaxcala": ["Tlaxcala", "Apizaco", "Huamantla", "Zacatelco"],
  "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Orizaba", "Boca del Río", "Poza Rica"],
  "Yucatán": ["Mérida", "Valladolid", "Tizimín", "Progreso", "Kanasín"],
  "Zacatecas": ["Zacatecas", "Guadalupe", "Fresnillo", "Jerez"]
}

export const MEXICAN_STATES = Object.keys(MEXICAN_STATES_AND_CITIES)
